
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
public class bangundatar extends javax.swing.JFrame {

  //  private double a;

    /**
     * Creates new form bangundatar
     */
    double luas,a,keliling,p,l,lpp,kpp,luasp,kelilingp,sp,as,ts,s1,s2,s3,ls,ks;
    double[]della=new double[1000];
    public bangundatar() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl = new javax.swing.JTextField();
        next = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        k_persegi = new javax.swing.JTextField();
        Hitung = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        sisi_persegi = new javax.swing.JTextField();
        l_persegi = new javax.swing.JTextField();
        Hapus = new javax.swing.JButton();
        jLabel96 = new javax.swing.JLabel();
        next3 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        sisib = new javax.swing.JTextField();
        d1 = new javax.swing.JTextField();
        d2 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        kbk = new javax.swing.JTextField();
        lbk = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jLabel94 = new javax.swing.JLabel();
        next4 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jLabel103 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        alas = new javax.swing.JTextField();
        tinggi = new javax.swing.JTextField();
        sisi1 = new javax.swing.JTextField();
        sisi2 = new javax.swing.JTextField();
        sisi3 = new javax.swing.JTextField();
        lsegitiga = new javax.swing.JTextField();
        ksegitiga = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel91 = new javax.swing.JLabel();
        next5 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jLabel106 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        kjg = new javax.swing.JTextField();
        alasj = new javax.swing.JTextField();
        tinggij = new javax.swing.JTextField();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        sm = new javax.swing.JTextField();
        ljg = new javax.swing.JTextField();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jLabel92 = new javax.swing.JLabel();
        next6 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Tfpanjang = new javax.swing.JTextField();
        Tflebar = new javax.swing.JTextField();
        Tfluas = new javax.swing.JTextField();
        Tfkeliling = new javax.swing.JTextField();
        bthitung = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        jLabel97 = new javax.swing.JLabel();
        next7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel114 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        l_lingkaran = new javax.swing.JTextField();
        k_keliling = new javax.swing.JTextField();
        hitung_lingkaran = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jari = new javax.swing.JTextField();
        jLabel98 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel117 = new javax.swing.JLabel();
        jLabel118 = new javax.swing.JLabel();
        jLabel119 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        kll = new javax.swing.JTextField();
        dia1 = new javax.swing.JTextField();
        dia2 = new javax.swing.JTextField();
        sl1 = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        sl2 = new javax.swing.JTextField();
        lll = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();
        jLabel90 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel120 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        jLabel122 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        kelt = new javax.swing.JTextField();
        jss = new javax.swing.JTextField();
        ps1 = new javax.swing.JTextField();
        ps2 = new javax.swing.JTextField();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        tp = new javax.swing.JTextField();
        luast = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jLabel93 = new javax.swing.JLabel();
        next2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel99 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();

        jl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("KELILING                :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 410, 180, 20));

        jLabel2.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2.setText("PERSEGI");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 180, 70));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("RUMUS LUAS        :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, 170, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("RUMUS KELILING :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, 210, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("SISI x SISI");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 150, 120, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("4  X SISI");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 200, 70, 20));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("MASUKKAN SISI    :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, 180, 20));

        k_persegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k_persegiActionPerformed(evt);
            }
        });
        jPanel1.add(k_persegi, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 410, 220, 30));

        Hitung.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Hitung.setText("HITUNG");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });
        jPanel1.add(Hitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 250, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("HASIL");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 300, 70, 20));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText(" LUAS                       :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 350, 190, 30));

        sisi_persegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sisi_persegiActionPerformed(evt);
            }
        });
        jPanel1.add(sisi_persegi, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 250, 220, 30));

        l_persegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_persegiActionPerformed(evt);
            }
        });
        jPanel1.add(l_persegi, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 350, 220, 30));

        Hapus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Hapus.setText("HAPUS");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        jPanel1.add(Hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 500, -1, -1));

        jLabel96.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SE.png"))); // NOI18N
        jPanel1.add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        next3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        next3.setText("NEXT");
        next3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next3ActionPerformed(evt);
            }
        });
        jPanel1.add(next3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 500, -1, -1));

        jButton24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton24.setText("x");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 10, 40, -1));

        jLabel100.setIcon(new javax.swing.ImageIcon(getClass().getResource("/awan.png"))); // NOI18N
        jPanel1.add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -50, -1, -1));

        jLabel101.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture1.png"))); // NOI18N
        jPanel1.add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, 440, -1, -1));

        jLabel104.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bunga Daffodil.png"))); // NOI18N
        jPanel1.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, -1));

        next.addTab("Persegi", jPanel1);

        jPanel5.setBackground(new java.awt.Color(0, 153, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(102, 51, 0));
        jLabel35.setText("BELAH KETUPAT");
        jPanel5.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel45.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel45.setText("RUMUS KELILING             :");
        jPanel5.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        jLabel46.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel46.setText("RUMUS LUAS                     : ");
        jPanel5.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, -1));

        jLabel47.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel47.setText("1/2 x DIAGONAL 1 x DIAGONAL 2");
        jPanel5.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, -1, -1));

        jLabel48.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel48.setText("4 x SISI");
        jPanel5.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, -1, -1));

        jLabel50.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel50.setText("SISI                                       :");
        jPanel5.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, -1));

        jLabel52.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel52.setText("MASUKKAN DIAGONAL 1 :");
        jPanel5.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

        jLabel53.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel53.setText("MASUKKAN DIAGONAL 2 :");
        jPanel5.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        jButton13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton13.setText("HITUNG");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 310, -1, -1));

        sisib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sisibActionPerformed(evt);
            }
        });
        jPanel5.add(sisib, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 220, 30));

        d1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d1ActionPerformed(evt);
            }
        });
        jPanel5.add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 220, 30));

        d2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d2ActionPerformed(evt);
            }
        });
        jPanel5.add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 220, 30));

        jLabel49.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel49.setText("HASIL");
        jPanel5.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, -1, -1));

        jLabel51.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel51.setText("KELILING                            :");
        jPanel5.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, -1, -1));

        jLabel54.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel54.setText("LUAS                                    :");
        jPanel5.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, -1));

        kbk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbkActionPerformed(evt);
            }
        });
        jPanel5.add(kbk, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, 220, 30));

        lbk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbkActionPerformed(evt);
            }
        });
        jPanel5.add(lbk, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 220, 30));

        jButton11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton11.setText("HAPUS");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 560, -1, -1));

        jLabel94.setIcon(new javax.swing.ImageIcon(getClass().getResource("/er.png"))); // NOI18N
        jPanel5.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 150, -1, -1));

        next4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        next4.setText("NEXT");
        next4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next4ActionPerformed(evt);
            }
        });
        jPanel5.add(next4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 560, -1, -1));

        jButton23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton23.setText("x");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 10, 40, -1));

        jLabel103.setIcon(new javax.swing.ImageIcon(getClass().getResource("/awan.png"))); // NOI18N
        jPanel5.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -30, -1, -1));

        jLabel105.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture1.png"))); // NOI18N
        jPanel5.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(-290, 440, -1, -1));

        jLabel107.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iris.png"))); // NOI18N
        jPanel5.add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 310, -1, -1));

        next.addTab("Belah Ketupat", jPanel5);

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 51, 0));
        jLabel18.setText("SEGITIGA");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setText("1/2 x ALAS x TINGGI");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 70, -1, 30));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setText("RUMUS LUAS           :");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, -1, -1));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setText("KELILING                  :");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 530, 200, -1));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel25.setText("SISI 1 + SISI 2 + SISI 3");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 110, -1, -1));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel26.setText("RUMUS KELILING   :");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, -1, -1));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel27.setText("MASUKKAN ALAS    :");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, -1, 20));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel28.setText("MASUKKAN TINGGI :");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, -1, -1));

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel29.setText("MASUKKAN SISI 1    :");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, -1, -1));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel30.setText("MASUKKAN SISI 2    :");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, -1, -1));

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel31.setText("MASUKKAN SISI 3    :");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, -1, -1));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel32.setText("HASIL");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 440, -1, -1));

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel33.setText("LUAS                          :");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 480, 220, -1));

        alas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alasActionPerformed(evt);
            }
        });
        jPanel3.add(alas, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 150, 230, 30));

        tinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinggiActionPerformed(evt);
            }
        });
        jPanel3.add(tinggi, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 200, 230, 30));

        sisi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sisi1ActionPerformed(evt);
            }
        });
        jPanel3.add(sisi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 260, 230, 30));

        sisi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sisi2ActionPerformed(evt);
            }
        });
        jPanel3.add(sisi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 320, 230, 30));

        sisi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sisi3ActionPerformed(evt);
            }
        });
        jPanel3.add(sisi3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 380, 230, 30));

        lsegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lsegitigaActionPerformed(evt);
            }
        });
        jPanel3.add(lsegitiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 480, 230, 30));
        jPanel3.add(ksegitiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 530, 230, 30));

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setText("HITUNG");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 250, -1, -1));

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setText("HAPUS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 590, -1, -1));

        jLabel91.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TIGA.png"))); // NOI18N
        jPanel3.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        next5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        next5.setText("NEXT");
        next5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next5ActionPerformed(evt);
            }
        });
        jPanel3.add(next5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 590, -1, -1));

        jButton22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton22.setText("x");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 10, 40, -1));

        jLabel106.setIcon(new javax.swing.ImageIcon(getClass().getResource("/awan.png"))); // NOI18N
        jPanel3.add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, -1, -1));

        jLabel108.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture1.png"))); // NOI18N
        jPanel3.add(jLabel108, new org.netbeans.lib.awtextra.AbsoluteConstraints(-290, 470, -1, -1));

        jLabel109.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bunga Daffodil.png"))); // NOI18N
        jPanel3.add(jLabel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 280, -1, -1));

        next.addTab("Segitiga", jPanel3);

        jPanel8.setBackground(new java.awt.Color(0, 153, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel79.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(102, 51, 0));
        jLabel79.setText("JAJAR GENJANG");
        jPanel8.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel80.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel80.setText("MASUKKAN SISI MIRING :");
        jPanel8.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, -1, 40));

        jLabel81.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel81.setText("( 2 x ALAS) + ( 2 x SISI MIRING)");
        jPanel8.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, -1, -1));

        jLabel82.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel82.setText("RUMUS LUAS                     :");
        jPanel8.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        jLabel83.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel83.setText("KELILING                           :");
        jPanel8.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 240, -1));

        jLabel84.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel84.setText("RUMUS KELILING             :");
        jPanel8.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, 30));

        jLabel85.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel85.setText("MASUKKAN ALAS             :");
        jPanel8.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        jLabel86.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel86.setText("MASUKKAN TINGGI          :");
        jPanel8.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, -1));
        jPanel8.add(kjg, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 470, 240, 30));
        jPanel8.add(alasj, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 240, 30));
        jPanel8.add(tinggij, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 240, 30));

        jLabel87.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel87.setText("HASIL");
        jPanel8.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, -1, -1));

        jLabel88.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel88.setText("ALAS x TINGGI");
        jPanel8.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, -1, -1));

        jLabel89.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel89.setText("LUAS                                   :");
        jPanel8.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 240, 20));

        sm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smActionPerformed(evt);
            }
        });
        jPanel8.add(sm, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 240, 30));

        ljg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ljgActionPerformed(evt);
            }
        });
        jPanel8.add(ljg, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 410, 240, 30));

        jButton20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton20.setText("HITUNG");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 240, -1, -1));

        jButton21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton21.setText("HAPUS");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 550, -1, -1));

        jLabel92.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JAR.png"))); // NOI18N
        jPanel8.add(jLabel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 250, 590, 310));

        next6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        next6.setText("NEXT");
        next6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next6ActionPerformed(evt);
            }
        });
        jPanel8.add(next6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 550, -1, -1));

        jButton14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton14.setText("x");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 10, 40, -1));

        jLabel111.setIcon(new javax.swing.ImageIcon(getClass().getResource("/awan.png"))); // NOI18N
        jPanel8.add(jLabel111, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, -1, -1));

        jLabel112.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture1.png"))); // NOI18N
        jPanel8.add(jLabel112, new org.netbeans.lib.awtextra.AbsoluteConstraints(-280, 430, -1, -1));

        jLabel113.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iris.png"))); // NOI18N
        jPanel8.add(jLabel113, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, -1));

        next.addTab("Jajar Genjang", jPanel8);

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("2 (PANJANG + LEBAR)");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, 270, 30));

        jLabel11.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 0, 0));
        jLabel11.setText("PERSEGI PANJANG");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 230, 60));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("RUMUS LUAS                :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 270, 30));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("HASIL");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 340, 70, 30));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("PANJANG x LEBAR");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, 270, 30));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("RUMUS KELILING        :");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 270, 30));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("MASUKKAN PANJANG :");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 270, 30));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setText("MASUKKAN LEBAR      :");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 270, 30));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setText("KELILNG                       :");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 230, -1));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setText("LUAS                              :");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 210, -1));

        Tfpanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfpanjangActionPerformed(evt);
            }
        });
        jPanel2.add(Tfpanjang, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, 230, 30));

        Tflebar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TflebarActionPerformed(evt);
            }
        });
        jPanel2.add(Tflebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 290, 230, 30));

        Tfluas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfluasActionPerformed(evt);
            }
        });
        jPanel2.add(Tfluas, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 390, 230, 30));
        jPanel2.add(Tfkeliling, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 450, 230, 30));

        bthitung.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bthitung.setText("HITUNG");
        bthitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthitungActionPerformed(evt);
            }
        });
        jPanel2.add(bthitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 250, -1, -1));

        bthapus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bthapus.setText("HAPUS");
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });
        jPanel2.add(bthapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 530, -1, -1));

        jLabel97.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fr.png"))); // NOI18N
        jPanel2.add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        next7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        next7.setText("NEXT");
        next7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next7ActionPerformed(evt);
            }
        });
        jPanel2.add(next7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 530, -1, -1));

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton9.setText("x");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 10, 40, -1));

        jLabel114.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture1.png"))); // NOI18N
        jPanel2.add(jLabel114, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, 420, -1, -1));

        jLabel115.setIcon(new javax.swing.ImageIcon(getClass().getResource("/awan.png"))); // NOI18N
        jPanel2.add(jLabel115, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -40, -1, -1));

        jLabel116.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bunga Daffodil.png"))); // NOI18N
        jPanel2.add(jLabel116, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 210, -1, -1));

        next.addTab("Persegi Panjang", jPanel2);

        jPanel4.setBackground(new java.awt.Color(0, 153, 255));
        jPanel4.setMinimumSize(new java.awt.Dimension(1200, 700));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(102, 0, 0));
        jLabel34.setText("LINGKARAN");
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        jLabel36.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel36.setText("KELILING                :");
        jPanel4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 210, -1));

        jLabel37.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel37.setText("RUMUS KELILING :");
        jPanel4.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, 30));

        jLabel38.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel38.setText("JARI-JARI               :");
        jPanel4.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, -1, -1));

        jLabel39.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel39.setText("PHI x 2 x JARI ");
        jPanel4.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, -1, 30));

        jLabel40.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel40.setText("PHI x JARI x JARI");
        jPanel4.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, -1, -1));
        jPanel4.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        jLabel42.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel42.setText("RUMUS LUAS         :");
        jPanel4.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, 30));

        jLabel43.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel43.setText("HASIL");
        jPanel4.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, -1, -1));

        jLabel44.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel44.setText("LUAS                        :");
        jPanel4.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 210, -1));

        l_lingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_lingkaranActionPerformed(evt);
            }
        });
        jPanel4.add(l_lingkaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 220, 30));

        k_keliling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k_kelilingActionPerformed(evt);
            }
        });
        jPanel4.add(k_keliling, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, 220, 30));

        hitung_lingkaran.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        hitung_lingkaran.setText("HITUNG");
        hitung_lingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitung_lingkaranActionPerformed(evt);
            }
        });
        jPanel4.add(hitung_lingkaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 290, -1, -1));

        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton8.setText("HAPUS");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 510, -1, -1));

        jari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jariActionPerformed(evt);
            }
        });
        jPanel4.add(jari, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 210, 30));

        jLabel98.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ling.png"))); // NOI18N
        jPanel4.add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 160, -1, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("NEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 510, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("x");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 10, 40, -1));

        jLabel117.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture1.png"))); // NOI18N
        jPanel4.add(jLabel117, new org.netbeans.lib.awtextra.AbsoluteConstraints(-280, 410, -1, -1));

        jLabel118.setIcon(new javax.swing.ImageIcon(getClass().getResource("/awan.png"))); // NOI18N
        jPanel4.add(jLabel118, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -40, -1, -1));

        jLabel119.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iris.png"))); // NOI18N
        jPanel4.add(jLabel119, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        next.addTab("Lingkaran", jPanel4);

        jPanel6.setBackground(new java.awt.Color(0, 153, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel55.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(102, 0, 0));
        jLabel55.setText("LAYANG - LAYANG");
        jPanel6.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jLabel56.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel56.setText("RUMUS KELILING              :");
        jPanel6.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 240, 30));

        jLabel57.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel57.setText("RUMUS LUAS                      :");
        jPanel6.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 240, 30));

        jLabel58.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel58.setText("1/2 x DIAGONAL 1 x DIAGONAL 2");
        jPanel6.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, -1, -1));

        jLabel59.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel59.setText("2 x (SISI 1 + SISI 2)");
        jPanel6.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, -1, 20));

        jLabel60.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel60.setText("MASUKKAN SISI 2              :");
        jPanel6.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, -1, -1));

        jLabel61.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel61.setText("MASUKKAN DIAGONAL 1 :");
        jPanel6.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        jLabel62.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel62.setText("MASUKKAN DIAGONAL 2 :");
        jPanel6.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));

        jLabel63.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel63.setText("MASUKKAN SISI 1              :");
        jPanel6.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        kll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kllActionPerformed(evt);
            }
        });
        jPanel6.add(kll, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 540, 260, 30));

        dia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dia1ActionPerformed(evt);
            }
        });
        jPanel6.add(dia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 260, 30));

        dia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dia2ActionPerformed(evt);
            }
        });
        jPanel6.add(dia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 260, 30));

        sl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sl1ActionPerformed(evt);
            }
        });
        jPanel6.add(sl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 260, 30));

        jLabel64.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel64.setText("KELILING                            :");
        jPanel6.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, 250, -1));

        jLabel65.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel65.setText("HASIL");
        jPanel6.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, -1, -1));

        jLabel66.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel66.setText("LUAS                                    :");
        jPanel6.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, 250, -1));

        sl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sl2ActionPerformed(evt);
            }
        });
        jPanel6.add(sl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 260, 30));

        lll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lllActionPerformed(evt);
            }
        });
        jPanel6.add(lll, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 490, 260, 30));

        jButton15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton15.setText("HAPUS");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 560, -1, -1));

        jLabel90.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Y.png"))); // NOI18N
        jPanel6.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("x");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 10, 40, -1));

        jLabel120.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture1.png"))); // NOI18N
        jPanel6.add(jLabel120, new org.netbeans.lib.awtextra.AbsoluteConstraints(-280, 430, -1, -1));

        jLabel121.setIcon(new javax.swing.ImageIcon(getClass().getResource("/awan.png"))); // NOI18N
        jPanel6.add(jLabel121, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -40, -1, -1));

        jLabel122.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bunga Daffodil.png"))); // NOI18N
        jPanel6.add(jLabel122, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jButton16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton16.setText("HAPUS");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 560, -1, -1));

        jButton19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton19.setText("HITUNG");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 350, -1, -1));

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton6.setText("NEXT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 560, -1, -1));

        next.addTab("Layang-Layang", jPanel6);

        jPanel7.setBackground(new java.awt.Color(0, 153, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel67.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(102, 51, 0));
        jLabel67.setText("TRAPESIUM");
        jPanel7.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        jLabel68.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel68.setText("RUMUS KELILING          :");
        jPanel7.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, -1, -1));

        jLabel69.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel69.setText("RUMUS LUAS                  :");
        jPanel7.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, -1, -1));

        jLabel70.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel70.setText("1/2 x JUMLAH SISI SEJAJAR x TINGGI");
        jPanel7.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 60, -1, -1));

        jLabel71.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel71.setText("JUMLAH SELURUH SISI ");
        jPanel7.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 110, -1, -1));

        jLabel72.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel72.setText("KELILING                         :");
        jPanel7.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 450, 240, -1));

        jLabel73.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel73.setText("JUMLAH SISI SEJAJAR  :");
        jPanel7.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, -1, -1));

        jLabel74.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel74.setText("PANJANG SISI 1              :");
        jPanel7.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, -1, -1));

        jLabel75.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel75.setText("PANJANG SISI 2              :");
        jPanel7.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, -1, -1));

        kelt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keltActionPerformed(evt);
            }
        });
        jPanel7.add(kelt, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 450, 240, 30));

        jss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jssActionPerformed(evt);
            }
        });
        jPanel7.add(jss, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 160, 240, 30));

        ps1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ps1ActionPerformed(evt);
            }
        });
        jPanel7.add(ps1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, 240, 30));

        ps2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ps2ActionPerformed(evt);
            }
        });
        jPanel7.add(ps2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 310, 240, 30));

        jLabel76.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel76.setText("TINGGI                             :");
        jPanel7.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, -1, -1));

        jLabel77.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel77.setText("HASIL");
        jPanel7.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 360, -1, -1));

        jLabel78.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel78.setText("LUAS                                 :");
        jPanel7.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 240, -1));

        tp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpActionPerformed(evt);
            }
        });
        jPanel7.add(tp, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 240, 30));

        luast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luastActionPerformed(evt);
            }
        });
        jPanel7.add(luast, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 400, 240, 30));

        jButton17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton17.setText("HITUNG");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 250, -1, -1));

        jButton18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton18.setText("HAPUS");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 520, -1, -1));

        jLabel93.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe.png"))); // NOI18N
        jPanel7.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        next2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        next2.setText("KEMBALI");
        next2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next2ActionPerformed(evt);
            }
        });
        jPanel7.add(next2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 520, -1, -1));

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton7.setText("x");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 10, 40, -1));

        jLabel99.setIcon(new javax.swing.ImageIcon(getClass().getResource("/awan.png"))); // NOI18N
        jPanel7.add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, -40, -1, -1));

        jLabel95.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture1.png"))); // NOI18N
        jPanel7.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 430, -1, -1));

        jLabel110.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iris.png"))); // NOI18N
        jPanel7.add(jLabel110, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 270, -1, -1));

        next.addTab("Trapesium", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(next)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void k_persegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k_persegiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_k_persegiActionPerformed

    private void sisi_persegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sisi_persegiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sisi_persegiActionPerformed

    private void l_persegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_persegiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l_persegiActionPerformed

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        // TODO add your handling code here:
  sp=Double.parseDouble(sisi_persegi.getText());
       luasp =sp* sp;
       kelilingp=4*sp;
       l_persegi.setText(String.valueOf(luasp)+" cm");
       k_persegi.setText(String.valueOf(kelilingp)+" cm");    
    }//GEN-LAST:event_HitungActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
     sisi_persegi.setText(" ");
l_persegi.setText(" ");
k_persegi.setText(" ");   
    }//GEN-LAST:event_HapusActionPerformed

    private void TfpanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfpanjangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfpanjangActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
        // TODO add your handling code here:
        Tfpanjang.setText("");
        Tflebar.setText("");
        Tfluas.setText("");
        Tfkeliling.setText("");
    }//GEN-LAST:event_bthapusActionPerformed

    private void tinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinggiActionPerformed

    private void sisi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sisi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sisi1ActionPerformed

    private void sisi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sisi2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sisi2ActionPerformed

    private void jlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlActionPerformed

    private void sisibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sisibActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sisibActionPerformed

    private void d1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d1ActionPerformed

    private void d2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d2ActionPerformed

    private void kllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kllActionPerformed

    private void dia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dia1ActionPerformed

    private void dia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dia2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dia2ActionPerformed

    private void sl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sl1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sl1ActionPerformed

    private void sl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sl2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sl2ActionPerformed

    private void lllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lllActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
dia1.setText(" ");
dia2.setText(" ");
sl1.setText(" ");
sl2.setText(" ");
lll.setText(" ");
kll.setText(" ");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void keltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keltActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keltActionPerformed

    private void jssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jssActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jssActionPerformed

    private void ps1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ps1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ps1ActionPerformed

    private void ps2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ps2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ps2ActionPerformed

    private void tpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpActionPerformed

    private void luastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_luastActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
     jss.setText(" ");
ps1.setText(" ");
ps2.setText(" ");
tp.setText(" ");
luast.setText(" ");
kelt.setText(" ");
    }//GEN-LAST:event_jButton18ActionPerformed

    private void bthitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthitungActionPerformed
 p=Double.parseDouble(Tfpanjang.getText());
  l=Double.parseDouble(Tflebar.getText());
       lpp =p* l;
       kpp=2*(p+l);
       Tfluas.setText(String.valueOf(lpp)+" cm");
       Tfkeliling.setText(String.valueOf(kpp)+" cm");
        // TODO add your handling code here:
         
        // TODO add your handling code here:
                
        
        
    }//GEN-LAST:event_bthitungActionPerformed

    private void l_lingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_lingkaranActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_l_lingkaranActionPerformed

    private void hitung_lingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitung_lingkaranActionPerformed

        a=Double.parseDouble(jari.getText());
       luas =3.14* a* a;
       keliling=2*3.14*a;
       l_lingkaran.setText(String.valueOf(luas)+" cm");
       k_keliling.setText(String.valueOf(keliling)+" cm");
       
// TODO add your handling code here:
    }//GEN-LAST:event_hitung_lingkaranActionPerformed

    private void k_kelilingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k_kelilingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_k_kelilingActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
l_lingkaran.setText(" ");
k_keliling.setText(" ");
jari.setText(" ");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        as=Double.parseDouble(alas.getText());
  ts=Double.parseDouble(tinggi.getText());
  s1=Double.parseDouble(sisi1.getText());
  s2=Double.parseDouble(sisi2.getText());
  s3=Double.parseDouble(sisi3.getText());
       ls = as * ts*1/2;
       ks=s1+ s2+ s3;
       lsegitiga.setText(String.valueOf(ls)+" cm");
       ksegitiga.setText(String.valueOf(ks)+" cm");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        lsegitiga.setText(" ");
ksegitiga.setText(" ");
alas.setText(" ");
tinggi.setText(" ");
sisi1.setText(" ");
sisi2.setText(" ");
sisi3.setText(" ");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        della[6]=Double.parseDouble(jss.getText());
  della[7]=Double.parseDouble(ps1.getText());
  della[8]=Double.parseDouble(ps2.getText());
  della[9]=Double.parseDouble(tp.getText());
       della[10] = della[6]* della[9]* 1/2;
       della[11]=(della[6]+ della[7] + della[8]);
       luast.setText(String.valueOf(della[10])+" cm");
       kelt.setText(String.valueOf(della[11])+" cm");
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        della[12]=Double.parseDouble(d1.getText());
  della[13]=Double.parseDouble(d2.getText());
  della[14]=Double.parseDouble(sisib.getText());
       della[15] = della[12]* della[13]* 1/2;
       della[16]= 4*della[14];
       lbk.setText(String.valueOf(della[15])+" cm");
       kbk.setText(String.valueOf(della[16])+" cm");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
d1.setText(" ");
d2.setText(" ");
sisib.setText(" ");
lbk.setText(" ");
kbk.setText(" ");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        della[17]=Double.parseDouble(alasj.getText());
  della[18]=Double.parseDouble(tinggij.getText());
  della[19]=Double.parseDouble(sm.getText());
       della[20] = della[17]* della[18];
       della[21]= (2*della[17])+(2*della[19]);
       ljg.setText(String.valueOf(della[20])+" cm");
       kjg.setText(String.valueOf(della[21])+" cm");
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
alasj.setText(" ");
tinggij.setText(" ");
sm.setText(" ");
ljg.setText(" ");
kjg.setText(" ");
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jariActionPerformed

    private void alasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alasActionPerformed

    private void sisi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sisi3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sisi3ActionPerformed

    private void lsegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lsegitigaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lsegitigaActionPerformed

    private void ljgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ljgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ljgActionPerformed

    private void smActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smActionPerformed

    private void lbkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbkActionPerformed

    private void TflebarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TflebarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TflebarActionPerformed

    private void TfluasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfluasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfluasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      next.setSelectedIndex(6);  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void next2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next2ActionPerformed
        // TODO add your handling code here:
        new beranda().show();
        this.dispose();
    }//GEN-LAST:event_next2ActionPerformed

    private void next3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next3ActionPerformed
        // TODO add your handling code here:
         next.setSelectedIndex(1); 
    }//GEN-LAST:event_next3ActionPerformed

    private void next4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next4ActionPerformed
        // TODO add your handling code here:
        next.setSelectedIndex(2);
    }//GEN-LAST:event_next4ActionPerformed

    private void next5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next5ActionPerformed
        // TODO add your handling code here:
         next.setSelectedIndex(3);
    }//GEN-LAST:event_next5ActionPerformed

    private void next6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next6ActionPerformed
        // TODO add your handling code here:
        next.setSelectedIndex(4);
    }//GEN-LAST:event_next6ActionPerformed

    private void next7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next7ActionPerformed
        // TODO add your handling code here:
        next.setSelectedIndex(5);
    }//GEN-LAST:event_next7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void kbkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kbkActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        della[22]=Double.parseDouble(dia1.getText());
  della[23]=Double.parseDouble(dia2.getText());
  della[24]=Double.parseDouble(sl1.getText());
  della[25]=Double.parseDouble(sl2.getText());
  
       della[26] = della[22]* della[23]* 1/2;
       della[27]= 2* (della[24]+della[25]);
       lll.setText(String.valueOf(della[26])+" cm");
       kll.setText(String.valueOf(della[27])+" cm");
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        next.setSelectedIndex(7); 
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bangundatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bangundatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bangundatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bangundatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bangundatar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hapus;
    private javax.swing.JButton Hitung;
    private javax.swing.JTextField Tfkeliling;
    private javax.swing.JTextField Tflebar;
    private javax.swing.JTextField Tfluas;
    private javax.swing.JTextField Tfpanjang;
    private javax.swing.JTextField alas;
    private javax.swing.JTextField alasj;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton bthitung;
    private javax.swing.JTextField d1;
    private javax.swing.JTextField d2;
    private javax.swing.JTextField dia1;
    private javax.swing.JTextField dia2;
    private javax.swing.JButton hitung_lingkaran;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jari;
    private javax.swing.JTextField jl;
    private javax.swing.JTextField jss;
    private javax.swing.JTextField k_keliling;
    private javax.swing.JTextField k_persegi;
    private javax.swing.JTextField kbk;
    private javax.swing.JTextField kelt;
    private javax.swing.JTextField kjg;
    private javax.swing.JTextField kll;
    private javax.swing.JTextField ksegitiga;
    private javax.swing.JTextField l_lingkaran;
    private javax.swing.JTextField l_persegi;
    private javax.swing.JTextField lbk;
    private javax.swing.JTextField ljg;
    private javax.swing.JTextField lll;
    private javax.swing.JTextField lsegitiga;
    private javax.swing.JTextField luast;
    private javax.swing.JTabbedPane next;
    private javax.swing.JButton next2;
    private javax.swing.JButton next3;
    private javax.swing.JButton next4;
    private javax.swing.JButton next5;
    private javax.swing.JButton next6;
    private javax.swing.JButton next7;
    private javax.swing.JTextField ps1;
    private javax.swing.JTextField ps2;
    private javax.swing.JTextField sisi1;
    private javax.swing.JTextField sisi2;
    private javax.swing.JTextField sisi3;
    private javax.swing.JTextField sisi_persegi;
    private javax.swing.JTextField sisib;
    private javax.swing.JTextField sl1;
    private javax.swing.JTextField sl2;
    private javax.swing.JTextField sm;
    private javax.swing.JTextField tinggi;
    private javax.swing.JTextField tinggij;
    private javax.swing.JTextField tp;
    // End of variables declaration//GEN-END:variables
}