
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
* To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
public class kuis extends javax.swing.JFrame {
     public kuis() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setUndecorated(true);
        initComponents();
//         initComponents();
        txtSoal.setText(""+Soal1[0]);
        A. setText(""+Soal1[1]);
        B. setText(""+Soal1[2]);
        C. setText(""+Soal1[3]);
        D. setText(""+Soal1[4]);
        txtAngka.setText(""+angka);
    }
int angka=1;
int Angka=0;
String Jawaban="";
String Betul ="";
int Benar=0;
int Salah=0;
//String[] soal=new String[];
String Soal1[]={"250 : 5 = ...?","A. 20", "B. 25", "C. 30","D. 50"};
String Soal2[]={"100 * 2 = ...?", "A. 200", "B. 250", "C. 300", "D. 230"};
String Soal3[]={"5420 + 350 = ...?", "A. 5740", "B. 5750", "C. 5800", "D. 5770"};
String Soal4[]={"75 - 28 = ...?", "A. 45", "B. 46", "C. 47", "D. 49"};
String Soal5[]={"Diketahui sisi persegi adalah 25. Berapakah luas dan kelilingnya?", "A. 625 dan 100", "B. 550 dan 150", "C. 600 dan 200", "D. 650 dan 250"};
String Soal6[]={"Sebuah kolam renang panjangnya 50 dan lebarnya 10. "
        + "\nBerapakah luas sebuah kolam tersebut?", "A. 300", "B. 250", "C. 500", "D. 450"};
String Soal7[]={"Sebuah segitiga memiliki alas 5 dan tinggi 6. Berapakah luasnya ?", "A. 30 ", "B. 15", "C. 20", "D. 25"};
String Soal8[]={"Diketahui alas jajar genjang 40 dan sisi miringnya 15. "
        + "\nBerapakah keliling jajar genjang tersebut?", "A. 110", "B. 120", "C. 150", "D. 130"};
String Soal9[]={"Diketahui sebuah layang-layang diagonal 1 = 4 dan diagonal 2 = 8, "
        +"\ndan memiliki sisi 1 = 3 dan sisi 2 = 9, maka berpakah luas dan kelilingnya?", "A. 18 dan 36", "B. 16 dan 24", "C. 16 dan 18", "D. 18 dan 24"};
String Soal10[]={"Sebuah lingkaran memiliki jari-jari 3. "
        + "\nBerapakah luas dan keliling lingkaran tersebut jika phi = 3,14?", "A. 28,26 dan 18,84", "B. 6,30 dan 25,10", "C. 6,15 dan 6,6", "D. 25,12 dan 6,28"};
String Soal11[]={"Sebuah balok memiliki panjang = 5, lebar = 3, dan tingginya = 2. "
        + "\nBerapakah volume balok tersebut?", "A. 30", "B. 35", "C. 40", "D. 45"};
String Soal12[]={"Diketahui panjang rusuk sebuah kubus 5, maka\n berapakah volume kubus tersebut?", "A. 130", "B. 125", "C. 135", "D. 140"};
/**
     * Creates new form kuis
     */
//    public void kuis() {
//        initComponents();
//        txtSoal.setText(""+Soal1[0]);
//        A. setText(""+Soal1[1]);
//        B. setText(""+Soal2[2]);
//        C. setText(""+Soal3[3]);
//        D. setText(""+Soal4[4]);
//        txtAngka.setText(""+angka);
//    }
public void Clear(){
    btngrup.clearSelection();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        btngrup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        nomor = new javax.swing.JTextField();
        txtAngka = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSoal = new javax.swing.JTextArea();
        kembali = new javax.swing.JButton();
        hasil = new javax.swing.JButton();
        next = new javax.swing.JButton();
        A = new javax.swing.JRadioButton();
        B = new javax.swing.JRadioButton();
        C = new javax.swing.JRadioButton();
        D = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        res = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 503));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomor.setEditable(false);
        nomor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        nomor.setText("No.");
        nomor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomorActionPerformed(evt);
            }
        });
        jPanel1.add(nomor, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 40, -1));

        txtAngka.setEditable(false);
        txtAngka.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtAngka.setText("N");
        txtAngka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAngkaActionPerformed(evt);
            }
        });
        jPanel1.add(txtAngka, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 30, -1));

        txtSoal.setEditable(false);
        txtSoal.setColumns(20);
        txtSoal.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtSoal.setRows(5);
        jScrollPane1.setViewportView(txtSoal);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 550, 230));

        kembali.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        kembali.setText("< Kembali ");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        jPanel1.add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, -1, -1));

        hasil.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        hasil.setText("Hasil");
        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });
        jPanel1.add(hasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 510, -1, -1));

        next.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        next.setText("> Selanjutnya");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel1.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 510, -1, -1));

        btngrup.add(A);
        A.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        A.setText("jRadioButton1");
        A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AActionPerformed(evt);
            }
        });
        jPanel1.add(A, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, -1));

        btngrup.add(B);
        B.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        B.setText("jRadioButton2");
        B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActionPerformed(evt);
            }
        });
        jPanel1.add(B, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, -1, -1));

        btngrup.add(C);
        C.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        C.setText("jRadioButton3");
        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });
        jPanel1.add(C, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, -1, -1));

        btngrup.add(D);
        D.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        D.setText("jRadioButton4");
        D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DActionPerformed(evt);
            }
        });
        jPanel1.add(D, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 420, -1, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("x");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 0, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 550, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 550, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 540, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 550, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 550, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pohon.png"))); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2.setText("LATIHAN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yu.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -30, -1, -1));

        res.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        res.setText("Reset Hasil");
        res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resActionPerformed(evt);
            }
        });
        jPanel1.add(res, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 510, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1388, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1106, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomorActionPerformed

    private void txtAngkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAngkaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAngkaActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
        Angka-=1;
        angka-=1;
        txtAngka.setText(""+angka);
        
        if(angka==0){
        txtAngka.setText(""+angka++);
    }
       
        if(angka==1){
            txtAngka.setText(""+angka);
   txtSoal.setText(""+Soal1[0]);
        A. setText(""+Soal1[1]);
        B. setText(""+Soal1[2]);
        C. setText(""+Soal1[3]);
        D. setText(""+Soal1[4]);
}else if(angka==2){
    txtSoal.setText(""+Soal2[0]);
        A. setText(""+Soal2[1]);
        B. setText(""+Soal2[2]);
        C. setText(""+Soal2[3]);
        D. setText(""+Soal2[4]);
      }else if(angka==3){  
     txtSoal.setText(""+Soal3[0]);
        A. setText(""+Soal3[1]);
        B. setText(""+Soal3[2]);
        C. setText(""+Soal3[3]);
        D. setText(""+Soal3[4]); 
     }else if(angka==4){ 
      txtSoal.setText(""+Soal4[0]);
        A. setText(""+Soal4[1]);
        B. setText(""+Soal4[2]);
        C. setText(""+Soal4[3]);
        D. setText(""+Soal4[4]);
      }else if(angka==5){   
     txtSoal.setText(""+Soal5[0]);
        A. setText(""+Soal5[1]);
        B. setText(""+Soal5[2]);
        C. setText(""+Soal5[3]);
        D. setText(""+Soal5[4]);
       }else if(angka==6){   
      txtSoal.setText(""+Soal6[0]);  
        A. setText(""+Soal6[1]);
        B. setText(""+Soal6[2]);
        C. setText(""+Soal6[3]);
        D. setText(""+Soal6[4]); 
         }else if(angka==7){ 
         txtSoal.setText(""+Soal7[0]);
        A. setText(""+Soal7[1]);
        B. setText(""+Soal7[2]);
        C. setText(""+Soal7[3]);
        D. setText(""+Soal7[4]);
       }else if(angka==8){  
        txtSoal.setText(""+Soal8[0]);
        A. setText(""+Soal8[1]);
        B. setText(""+Soal8[2]);
        C. setText(""+Soal8[3]);
        D. setText(""+Soal8[4]);
         }else if(angka==9){ 
        txtSoal.setText(""+Soal9[0]);
        A. setText(""+Soal9[1]);
        B. setText(""+Soal9[2]);
        C. setText(""+Soal9[3]);
        D. setText(""+Soal9[4]);
       }else if(angka==10){  
       txtSoal.setText(""+Soal10[0]);
        A. setText(""+Soal10[1]);
        B. setText(""+Soal10[2]);
        C. setText(""+Soal10[3]);
        D. setText(""+Soal10[4]);
       }else if(angka==11){ 
       txtSoal.setText(""+Soal11[0]);
        A. setText(""+Soal11[1]);
        B. setText(""+Soal11[2]);
        C. setText(""+Soal11[3]);
        D. setText(""+Soal11[4]);
        }else if(angka==12){ 
            txtAngka.setText(""+angka);
      txtSoal.setText(""+Soal12[0]);
        A. setText(""+Soal12[1]);
        B. setText(""+Soal12[2]);
        C. setText(""+Soal12[3]);
        D. setText(""+Soal12[4]);  
}
        else if(angka==13){ 
            txtAngka.setText(""+(--angka));
      txtSoal.setText(""+Soal12[0]);
        A. setText(""+Soal12[1]);
        B. setText(""+Soal12[2]);
        C. setText(""+Soal12[3]);
        D. setText(""+Soal12[4]);  
}
Clear();
    
    }//GEN-LAST:event_kembaliActionPerformed
//    if(angka==0){
//        txtAngka.setText(""+angka++);
//    }
        
    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        Angka+=1;
        angka+=1;
      txtAngka.setText(""+angka);
        if(Angka==1){
        
         if(D.isSelected()){
            Benar +=1;
        }
         else{
            Salah +=1;
        
        }Clear();
        }
    if(angka ==2){
        
    txtSoal.setText(""+Soal2[0]);
        A. setText(""+Soal2[1]);
        B. setText(""+Soal2[2]);
        C. setText(""+Soal2[3]);
        D. setText(""+Soal2[4]);
        txtAngka.setText(""+angka);
        
    }if(Angka ==2){
    if(A.isSelected()){
            Benar +=1;
        }else{
            Salah +=1;
       
        }Clear();
    }
    if(angka ==3){
        
    txtSoal.setText(""+Soal3[0]);
        A. setText(""+Soal3[1]);
        B. setText(""+Soal3[2]);
        C. setText(""+Soal3[3]);
        D. setText(""+Soal3[4]);
        txtAngka.setText(""+angka);
        
        }if(Angka ==3){
        if(D.isSelected()){
            Benar +=1;
        }else{
            Salah +=1;
        }Clear(); 
            }
        if(angka ==4){
        
    txtSoal.setText(""+Soal4[0]);
        A. setText(""+Soal4[1]);
        B. setText(""+Soal4[2]);
        C. setText(""+Soal4[3]);
        D. setText(""+Soal4[4]);
        txtAngka.setText(""+angka);
        
        }if(Angka ==4){
        if(C.isSelected()){
            Benar +=1;
        }else{
            Salah +=1;
        }  Clear();   
            }
        if(angka ==5){
        
    txtSoal.setText(""+Soal5[0]);
        A. setText(""+Soal5[1]);
        B. setText(""+Soal5[2]);
        C. setText(""+Soal5[3]);
        D. setText(""+Soal5[4]);
        txtAngka.setText(""+angka);
        
        }if(Angka ==5){
        if(A.isSelected()){
            Benar +=1;
        }else{
            Salah +=1;
            
         }Clear();
        }if(angka ==6){
        
    txtSoal.setText(""+Soal6[0]);
        A. setText(""+Soal6[1]);
        B. setText(""+Soal6[2]);
        C. setText(""+Soal6[3]);
        D. setText(""+Soal6[4]);
        txtAngka.setText(""+angka);
        
        }if(Angka ==6){
        if(C.isSelected()){
            Benar +=1;
        }else{
            Salah +=1;  
            
            }Clear();
        }
        if(angka ==7){
        
    txtSoal.setText(""+Soal7[0]);
        A. setText(""+Soal7[1]);
        B. setText(""+Soal7[2]);
        C. setText(""+Soal7[3]);
        D. setText(""+Soal7[4]);
        txtAngka.setText(""+angka);
        
        }if(Angka ==7){
        if(B.isSelected()){
            Benar +=1;
        }else{
            Salah +=1;
            
            }Clear();
        }
        if(angka ==8){
        
    txtSoal.setText(""+Soal8[0]);
        A. setText(""+Soal8[1]);
        B. setText(""+Soal8[2]);
        C. setText(""+Soal8[3]);
        D. setText(""+Soal8[4]);
        txtAngka.setText(""+angka);
        
        }if(Angka ==8){
        if(A.isSelected()){
            Benar +=1;
        }else{
            Salah +=1;
            
        }Clear();
        }if(angka ==9){
        
    txtSoal.setText(""+Soal9[0]);
        A. setText(""+Soal9[1]);
        B. setText(""+Soal9[2]);
        C. setText(""+Soal9[3]);
        D. setText(""+Soal9[4]);
        txtAngka.setText(""+angka);
        
        }if(Angka ==9){
        if(B.isSelected()){
            Benar +=1;
        }else{
            Salah +=1;
        }Clear(); 
            }if(angka ==10){
        
    txtSoal.setText(""+Soal10[0]);
        A. setText(""+Soal10[1]);
        B. setText(""+Soal10[2]);
        C. setText(""+Soal10[3]);
        D. setText(""+Soal10[4]);
        txtAngka.setText(""+angka);
        
        }if(Angka ==10){
        if(A.isSelected()){
            Benar +=1;
        }else{
            Salah +=1;
        }Clear(); 
            }
        if(angka ==11){
        
    txtSoal.setText(""+Soal11[0]);
        A. setText(""+Soal11[1]);
        B. setText(""+Soal11[2]);
        C. setText(""+Soal11[3]);
        D. setText(""+Soal11[4]);
        txtAngka.setText(""+angka);
        
        }if(Angka ==11){
        if(A.isSelected()){
            Benar +=1;
        }else{
            Salah +=1;
        }Clear();
            }
        if(angka ==12){
        
    txtSoal.setText(""+Soal12[0]);
        A. setText(""+Soal12[1]);
        B. setText(""+Soal12[2]);
        C. setText(""+Soal12[3]);
        D. setText(""+Soal12[4]);
        txtAngka.setText(""+(angka));
        
        }if(Angka ==12){
        if(B.isSelected()){
            Benar +=1;
        }else{
            Salah +=1;
        }
        Clear();
        }
         if(angka ==13){
        
    txtSoal.setText(""+Soal12[0]);
        A. setText(""+Soal12[1]);
        B. setText(""+Soal12[2]);
        C. setText(""+Soal12[3]);
        D. setText(""+Soal12[4]);
        txtAngka.setText(""+(--angka));
        
        }if(Angka ==12){
        if(B.isSelected()){
            Benar +=1;
        }else{
            Salah +=1;
        }
        Clear();
        }
    }//GEN-LAST:event_nextActionPerformed

    private void AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AActionPerformed
        // TODO add your handling code here:
        Jawaban ="A";
    }//GEN-LAST:event_AActionPerformed

    private void BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActionPerformed
        // TODO add your handling code here:
        Jawaban ="B";
    }//GEN-LAST:event_BActionPerformed

    private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed
        // TODO add your handling code here:
        Jawaban ="C";
    }//GEN-LAST:event_CActionPerformed

    private void DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DActionPerformed
        // TODO add your handling code here:
        Jawaban ="D";
    }//GEN-LAST:event_DActionPerformed

    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Betul :"+Benar+"\n"+"Salah : "+Salah);
    }//GEN-LAST:event_hasilActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resActionPerformed
Benar=0;
Salah=0;
        // TODO add your handling code here:
    }//GEN-LAST:event_resActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kuis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kuis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kuis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kuis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kuis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton A;
    private javax.swing.JRadioButton B;
    private javax.swing.JRadioButton C;
    private javax.swing.JRadioButton D;
    private javax.swing.ButtonGroup btngrup;
    private javax.swing.JButton hasil;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton kembali;
    private javax.swing.JButton next;
    private javax.swing.JTextField nomor;
    private javax.swing.JButton res;
    private javax.swing.JTextField txtAngka;
    private javax.swing.JTextArea txtSoal;
    // End of variables declaration//GEN-END:variables
}
